version: "3.8"
services:
  mirrorclone:
    image: natim2/mirrorclone:latest
    container_name: mirrorclone
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - /srv/link_appdata/mirrorcloneData/config:/config
      - /srv/link_appdata/mirrorcloneData/backups:/backups
      - /srv/link_appdata:/data
    environment:
      - TZ=Asia/Jerusalem
    privileged: true
    networks:
      - backup-network
networks:
  backup-network:
    driver: bridge
